name: Python app test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]
    
    env:
      MODE: "dev"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python_version: ${{ matrix.python-version }}
      
      - name: Install depenedencies
        run: |
          python -m pip install -- upgrade pip
      
      - name: Test App Code
        run: python ./app/tictactoe.py
